<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Soga.EntityFrameworkCore</PackageId>
    <Version>0.1.0-preview.1</Version>
    <Authors>Zhuwa Africa Limited</Authors>
    <Description>Entity Framework Core persistence integration for Soga.</Description>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>soga-package-icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <ProjectReference Include="..\Soga\Soga.csproj" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
    <None Include="..\..\assets\soga-package-icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
